### ISSUE TITLE
Update planter config with commands

### ISSUE THREAD

**Issue by crejer** [team-octoo/planter-cli#22]
It would be nice if we had the possibility to add/remove folders in our planter config file by using the cli.

For example:

`planter folder:add elements/<newElementGroup>`

this could add a new entry in the `components` part of the config file with:

![image](https://github.com/team-octoo/planter-cli/assets/2621483/40220dc2-fdd3-4a58-87df-ec4f0ba210b9)

**Comment by Jozzeh** [comment]
Please update.    
The feature has been added in version 1.0.11    

command:   
> planter plant:folder folderName  

Where "folderName" is the name of the new folder.  
if a slash / is used in the folderName, this will create a subfolder.
