### ISSUE TITLE
Poweruser option to create components

### ISSUE THREAD

**Issue by RaevensRobbe** [team-octoo/planter-cli#23]
Would it be possible for users who are familiar with the cli to make it work even faster using power commands like:

- planter plant:component:basic componentName
- planter plant:component basic componentName

This can be useful so we don't have to select the component type in the dropdown each time 😄

**Comment by crejer** [comment]
Nice idea,

Personaly I would add it as an option with `--folder <folderName>` as you can specify multiple folders.
If that folder doesn't exist, it could be added to the configuration :)

**Comment by Jozzeh** [comment]
Thanks for the idea!   
This has been implemented in v1.0.16   

To create a component you can do following commands:  
- "planter plant:component componentName"   
- "planter plant:component componentName --folder folderName"   
- "planter plant:component componentName folderName"   

If the foldername is not found, you will be prompted to choose a folder (default create-component behavior).    
Text is prone to error + creating a new folder and adding it to the planter config, is a diffirent command.
